<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<br />
<br />
<center><h1>توزيع الذهب</h1>
<form method="post" action="gga.php"><div id="block"><textarea name="news" id="notice">
<?php echo $this->siteNews; ?>
</textarea>
<p class="btn">
<input id="btn_save" type="image" value="" name="s1" src="core-s/st-s/x.gif" class="dynamic_img" alt="<?php echo text_save_lang;?>"

<br/>
<?php if ( $this->saved ){echo text_newssaved_lang;}?>
</p>
</div>
</form>
</center>
</body>
</html>