<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div id="content" align="right"><h1>جوائز السيرفر</h1>

<?php if ($_GET['t'] == 1) { ?>

</div> 

<?php }else{ ?>
<div class="wholebox"><p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة
</div>




<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة
</div>


<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة

</div>



<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة

</div>


<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة

</div>

<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
هنا يكتب وصف الجائزة

</div>


<p class="f10 e b">هنا يكتب عنوان الجائزة</p>
<div class="f10"> 
	هنا يكتب وصف الجائزة

</div>




</div> 
</div>
<?php } ?>
</body>
</html>