<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php

###############################################

##   s@smartservs.com    &&   BASEL WAEL##

###############################################



if ( !$this->requestPaymentProvider )

{
?>
<div class="messagebox">
 
</div>
<?php
    echo "<div id=\"container\"></div>\r\n\r\n<noscript>Please enable JavaScript in your Browser to continue.</noscript> \r\n";
?>
<script type="text/javascript">function createRequestObject(){var browser=navigator.appName;if(browser=='Microsoft Internet Explorer'){return new ActiveXObject('Microsoft.XMLHTTP');}else{return new XMLHttpRequest();}
return null;}
function loadProviderHtml(){http.open('get','payment.php?c&p=<?php echo $_GET['p']; ?>&pg=<?php echo $_GET['pg']; ?>');http.onreadystatechange=handleLoadProviderHtmlResponse;http.send(null);}
function handleLoadProviderHtmlResponse(){if(http.readyState==4){if(http.status==200){var response=http.responseText;var target=document.getElementById('container');target.innerHTML=response;document.payment.submit();}else{var target=document.getElementById('container');target.innerHTML='Error: unable to load payment provider. ('+http.statusText+')';}}}
var http=createRequestObject();loadProviderHtml();</script>
<?php 
}

else if ( $this->providerType == "paylink" || $this->providerType == "apple_pay" )
{
    ?>
    <style>
        html, body
        {
            font-size: inherit !important;
            zoom: normal !important;
            
        }

        .messagebox , #container {
            display: none  !important;
        }

        body.manual
        {
            zoom: normal !important;
        }
    </style>
    <?php
}
else if ( $this->providerType == "cashu" )

{

    $price = $this->package['cost'];

    $token = md5( sprintf( "%s:%s:%s:%s", $this->payment['merchant_id'], $price, strtolower( $this->payment['currency'] ), $this->payment['testMode'] ? $this->payment['testKey'] : $this->payment['key'] ) );

    $dtest = sprintf( "%s ".text_gold_lang, $this->package['gold'] );

    echo "<form action=\"https://www.cashu.com/cgi-bin/pcashu.cgi\" method=\"post\" name=\"payment\">\r\n\t";

    if ( $this->payment['testMode'] )

    {

        echo "<input type=\"hidden\" name=\"test_mode\" value=\"1\">";

    }

    echo "\t";

    if ( trim( $this->payment['serviceName'] ) != "" )

    {

        echo "<input type=\"hidden\" name=\"service_name\" value=\"";

        echo $this->payment['serviceName'];

        echo "\">";

    }

    echo "\t<input type=\"hidden\" name=\"merchant_id\" value=\"";

    echo $this->payment['merchant_id'];

    echo "\">\r\n    <input type=\"hidden\" name=\"currency\" value=\"";

    echo $this->payment['currency'];

    echo "\">\r\n    <input type=\"hidden\" name=\"amount\" value=\"";

    echo $price;

    echo "\">\r\n    <input type=\"hidden\" name=\"session_id\" value=\"";

    echo $this->secureId;

    echo "\">\r\n\t<input type=\"hidden\" name=\"token\" value=\"";

    echo $token;

    echo "\">\r\n    <input type=\"hidden\" name=\"display_text\" value=\"";

    echo $dtest;

    echo "\">\r\n\t<input type=\"hidden\" name=\"language\" value=\"";

    echo $this->appConfig['system']['lang'];

    echo "\">\r\n    <input type=\"hidden\" name=\"txt1\" value=\"";

    echo text_gold_lang;

    echo "\"></form>\r\n";

}

else if ( $this->providerType == "onecard" )

{

    $dt = date( "ymdHis" );

        $returnKey= base64_encode( $AppConfig['plus']['payment']['onecard']['returnKey'] );

    $price = $this->package['cost'];

    $token = md5( sprintf( "%s:%s:%s:%s", $this->payment['merchant_id'], $price, strtolower( $this->payment['currency'] ), $this->payment['testMode'] ? $this->payment['testKey'] : $this->payment['key'] ) );

    $dtest = sprintf( "%s ".text_gold_lang, $this->package['gold'] );

    $TransID = base64_encode( base64_decode( $this->secureId ).time( ) );

    $txt1 = base64_decode( $this->secureId )."-".$this->packageIndex."-".$price;

    $key = $this->payment['merchant_id'].$TransID.$price.$this->payment['currency'].$dt.$this->payment['key'];

    $token = md5( $key );

    echo "<form name=\"payment\" action=\"https://www.onecard.net/customer/integratedPayment.html\" method=\"post\">\r\n<input type=\"hidden\" name=\"OneCard_MProd\" value=\"Tatar War\">\r\n<input type=\"hidden\" name=\"OneCard_Amount\" value=\"";

    echo $price;

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_MerchID\" value=\"";

    echo $this->payment['merchant_id'];

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_HashKey\" value=\"";

    echo $token;

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_Timein\" value=\"";

    echo $dt;

    echo "\" >\r\n<input type=\"hidden\" name=\"OneCard_ReturnURL\" value = \"";

    echo $this->Domain."paymentservice.php";

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_TransID\" value=\"";

    echo $TransID;

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_Currency\" value=\"";

    echo $this->payment['currency'];

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_Field1\" value=\"";

    echo $this->secureId;

    echo "\">\r\n<input type=\"hidden\" name=\"OneCard_Field2\" value=\"";

    echo $returnKey;

    echo "\">\r\n<input id=\"Submit1\" type=\"submit\" value=\"submit\" />\r\n</form>\r\n";

}

else if ( $this->providerType == "paypal" )

{

    require_once( LIB_PATH."paypal.class.php" );

    $p = new paypal_class( );

    if ( $this->payment['testMode'] )

    {

        $p->paypal_url = "https://www.sandbox.paypal.com/cgi-bin/webscr";

    }

    else

    {

        $p->paypal_url = "https://www.paypal.com/cgi-bin/webscr";

    }
  
  if((int) @$this->package['goldplus'] > 0 ) {
        $this->package['gold'] = @$this->package['goldplus'];
    }
  

    $dtest = sprintf( "%s ".text_gold_lang, $this->package['gold'] );

    $this_script = $this->Domain."paymentservice_paypal.php";

    $p->add_field( "business", $this->payment['merchant_id'] );

    $p->add_field( "return", $this_script."?action=success" );

    $p->add_field( "cancel_return", $this_script."?action=cancel" );

    $p->add_field( "notify_url", $this_script."?action=ipn" );

    $p->add_field( "item_name", $dtest );

    $p->add_field( "custom", $this->secureId );

    $p->add_field( "bn", "btn_buynow_SM.gif" );

    $p->add_field( "amount", $this->package['cost'] );

    $p->add_field( "currency_code", $this->payment['currency'] );

    $p->submit_paypal_post( );

}
else if ( $this->providerType == "payGol" )
{
    ?>
    <script src="http://www.paygol.com/micropayment/js/paygol.js" type="text/javascript"></script>
<script src="http://www.paygol.com/micropayment/js/pg.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://www.paygol.com/micropayment/css/pg.css" type="text/css" media="screen">
<?php
	echo '<form name="pg_frm" method="post" action="https://www.paygol.com/pay" >';
	echo '<input type="hidden" name="pg_serviceid" value="'. $this->pg_serviceid .'">';
	echo '<input type="hidden" name="pg_currency" value="SAR">';
	echo '<input type="hidden" name="pg_name" value="'.$this->pg_name.'">';
	echo '<input type="hidden" name="pg_price" value="'. ($_GET['pg']+1) .'">';
	echo '<input type="hidden" name="pg_custom" value="'. $this->player->playerId .'">';
	echo '</form>';
}
?>
</body>
</html>
