<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
</head>
<body>
<?php
###############################################
##   s@smartservs.com    &&   BASEL WAEL##
###############################################

if (!isset($_GET['links']))
{
echo '<h1>'.LANGUI_PROFILE_T1.'</h1>';
if($this->fullView){echo '
    <div id="textmenu">
        <a href="profile.php" '.(($this->selectedTabIndex == 0 && !isset($_GET['tvq']))? 'class="selected"':'').'>'.LANGUI_PROFILE_T2.'</a> |
        <a href="profile.php?t=1" '.(($this->selectedTabIndex == 1) ? 'class="selected"':'').'>'.LANGUI_PROFILE_T3.'</a> |
        <a href="profile.php?t=2" '.(($this->selectedTabIndex == 2) ? 'class="selected"':'').'>الاعدادات</a>';
		echo ' | <a href="bprotect.php" '.(($this->selectedTabIndex == 101 )? 'class="selected"':'').'><font color="blue">الحماية</font></a>';
        if ( $this->data['active_plus_account'] )
        {
        echo ' | <a href="profile.php?links" '.(($this->selectedTabIndex == 3 )? 'class="selected"':'').'><font color="#FF6F0F">روابط مباشرة</font></a>';
		echo ' | <a href="notes.php" '.(($this->selectedTabIndex == 4 )? 'class="selected"':'').'><font color="#FF6F0F">دفتر الملاحظات</font></a>';
        }
		 
        echo '';
?><?php
        echo '
    </div>';
}
}
if (isset($_GET['links']))
{
?>
<h1>روابط مباشرة</h1><p></p><?php
echo "<p></p>\r\n<form action=\"profile.php?links\" method=\"POST\">\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"links\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th><a href=\"#\" onclick=\"return showManual(5,6);\"><img class=\"help\" src=\"core-s/st-s/x.gif\" alt=\"";
echo text_helptip_lang;
echo "\" title=\"";
echo text_helptip_lang;
echo "\"></a></th>\r\n\t\t\t<th colspan=\"2\">";
echo LANGUI_LNKS_T1;
echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
echo LANGUI_LNKS_T2;
echo "</td><td>";
echo LANGUI_LNKS_T3;
echo "</td><td>";
echo LANGUI_LNKS_T4;
echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
$_c = 1;
foreach ( $this->playerLinks as $link )
{
    echo "\t\t<tr>\r\n\t\t\t<td class=\"nr\"><input class=\"text\" type=\"text\" name=\"nr[]\" value=\"";
    echo $_c++;
    echo "\" size=\"1\" maxlength=\"3\"></td>\r\n\t\t\t<td class=\"nam\"><input class=\"text\" type=\"text\" name=\"linkname[]\" value=\"";
    echo htmlspecialchars( $link['linkName'] );
    echo "\" maxlength=\"30\"></td>\r\n\t\t\t<td class=\"link\"><input class=\"text\" type=\"text\" name=\"linkurl[]\" value=\"";
    echo htmlspecialchars( $link['linkHref'].( $link['linkSelfTarget'] ? "" : "*" ) );
    echo "\" maxlength=\"255\"></td>\r\n\t\t</tr>\r\n\t\t";
}
echo "\t\t<tr>\r\n\t\t\t<td class=\"nr\"><input class=\"text\" type=\"text\" name=\"nr[]\" value=\"";
echo $_c;
echo "\" size=\"1\" maxlength=\"3\"></td>\r\n\t\t\t<td class=\"nam\"><input class=\"text\" type=\"text\" name=\"linkname[]\" value=\"\" maxlength=\"30\"></td>\r\n\t\t\t<td class=\"link\"><input class=\"text\" type=\"text\" name=\"linkurl[]\" value=\"\" maxlength=\"255\"></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n<p class=\"btn\"><input type=\"image\" value=\"\" name=\"s1\" id=\"btn_ok\" class=\"dynamic_img\" src=\"core-s/st-s/x.gif\" alt=\"";
echo text_okdone_lang;
echo "\"></p>\r\n</form>";
echo "<span class='error'>1- يضاف * الى نهاية الرابط لفتح الوصله في نافذة جديدة.</span>";
} else if($this->selectedTabIndex == 0){

require_once (APP_PATH.'broswor.php');
$obj = new OS_BR();
$browser = $obj->showInfo('browser');
if ($browser != 'Internet Explorer') {
echo ' <script type="text/javascript">
        function getMouseCoords(e) {
            var coords = {};
            if (!e) var e = window.event;
            if (e.pageX || e.pageY) {
                coords.x = e.pageX;
                coords.y = e.pageY;
            }
            else if (e.clientX || e.clientY) {
                coords.x = e.clientX + document.body.scrollLeft + document.documentElement.scrollLeft;
                coords.y = e.clientY + document.body.scrollTop + document.documentElement.scrollTop;
            }
            return coords;
        }
        function med_mouseMoveHandler(e, desc_string) {
            var coords = getMouseCoords(e);
            var layer = _("medal_mouseover");
            layer.style.top = (coords.y + 25) + "px";
            layer.style.left = (coords.x - 20) + "px";
            layer.className = "";
            layer.innerHTML  = desc_string;
        }
        function med_closeDescription(){
            var layer = _("medal_mouseover");
            layer.className = "hide";
        }
        layer = document.createElement("div");
        layer.id = "medal_mouseover";
        layer.className = "hide";
        document.body.appendChild(layer);
    </script>';
}
echo '
    
    <table id="profile" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th colspan="2">'.LANGUI_PROFILE_T7.' '.$this->profileData['name'].'
				<tr><th colspan="2">
				'.((isset($this->profileData['player_type'])
				&& $this->data['player_type'] == PLAYERTYPE_ADMIN)?
				'<font color="red">
				'."( ♛ الإدارة ♛ )".'</tr>
				</font>':'').'
				'.((isset($this->profileData['is_blocked']) && $this->profileData['is_blocked'] == 1)? '<font color="#990000">'."( موقوف )".'</font>':'').'</th>

            </tr>
            <tr>

                        <td>التفاصيل:</td>
                        <td>الوصف:</td>
                </tr>
        </thead>
        <tbody>
                <tr>
                        <td class="empty"></td><td class="empty"></td>
                </tr>
                <tr>
                        <td class="details">
                    <table cellpadding="0" cellspacing="0">
                        <tbody>';
?>
                                <tbody>
<?php echo $this->profileData['name']; ?>
<tr><th>
</th>
                                                <td></td>
<?php

                               echo'                 
                             <tr>
                                <th>'.LANGUI_PROFILE_T10.' :</th>
                                <td>      '.  $this->profileData['rank']   .'</td>
                           </tr>
                            <tr>
                                <th>'.LANGUI_PROFILE_T11.' :</th>
                                <td>'.constant("tribe_".$this->profileData['tribe_id']).'</td>
                            </tr>
                            <tr>
                                <th>'.LANGUI_PROFILE_T12.' :</th>
                                <td>'.((0 < intval($this->profileData['alliance_id'])) ? '<a href="alliance.php?id='.$this->profileData['alliance_id'].'">'.$this->profileData['alliance_name'].'</a>' : '-').'</td>
                            </tr>
                            <tr>
                                <th>'.LANGUI_PROFILE_T13.' :</th>
                                <td>'.$this->villagesCount.'</td>
                            </tr>
                            <tr>
                                <th>'.LANGUI_PROFILE_T14.' :</th>
                                <td>'.$this->profileData['total_people_count'].'</td>
                             </tr>';     
                            if(0 < $this->profileData['age']){echo '
                            <tr>
                                <th>'.LANGUI_PROFILE_T15.' :</th>
                                <td>'.$this->profileData['age'].'</td>
                            </tr>';
                            }
                            if(0 < $this->profileData['gender']){
                                echo "\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<th>";
        echo LANGUI_PROFILE_T16;
        echo " :</th>\r\n\t\t\t\t\t\t<td>";
        echo $this->profileData['gender'] == 1 ? LANGUI_PROFILE_T17 : LANGUI_PROFILE_T18;

        echo "</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t";
    }
    echo "\t\t\t\t\t";
    if ( $this->profileData['house_name'] != "" )
    {
        echo "\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<th>";
        echo LANGUI_PROFILE_T19;
        echo " :</th>\r\n\t\t\t\t\t\t<td>";
        echo $this->profileData['house_name'];
        echo "</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t";
    }


    echo "\t\t\t\t\t<tr><td colspan=\"2\" class=\"empty\"></td></tr>";

    if ( $this->profileData['tribe_id'] != 5 )
    {
        echo "\t\t\t\t\t<tr></tr>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td colspan=\"2\"> ";
        if ( !$this->player->isAgent )
        {
            if ( $this->fullView )
            {
                echo "<a href=\"profile.php?t=1\">";
                echo LANGUI_PROFILE_T20;
                echo "</a>";    /*
                echo "<a href=\"img.php\">";
                echo "» تعديل الصورة الشخصيه";
                echo "</a>";      */
            }
            else
            {
                echo "<a href=\"msg.php?uid=";
                echo $this->profileData['id'];
                echo "\">";
                echo LANGUI_PROFILE_T21;
                echo "</a>";
            }
        }
        
    }
    echo "\t\t\t\t\t<tr><td colspan=\"2\" class=\"empty\"></td></tr>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td colspan=\"2\" class=\"desc2\"><div class=\"desc2div\">";
    echo $this->getProfileDescription( $this->profileData['description2'] );
    echo "</div></td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</tbody>\r\n\t\t\t\t</table>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"desc1\"><div>";
    echo $this->getProfileDescription( $this->profileData['description1'] );
    echo "</div></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"villages\">\r\n\t<thead>\r\n\t<tr><th colspan=\"5\">";
	echo "مجموعة القرى&nbsp";
    echo "(";
    echo ''.$this->villagesCount.'';
	echo ")";
    echo "</th></tr>\r\n\t<tr>\r\n\t\t<td>";
    echo LANGUI_PROFILE_T23;
    echo "</td>\r\n\t\t<td>موارد</td><td>ارساليات</td><td>";
    echo LANGUI_PROFILE_T14;
    echo "</td>\r\n\t\t<td>";
    echo LANGUI_PROFILE_T24;
    echo "</td>";
	if ( $this->isAdmin )
    {
	echo "<td></td>";
	}
	echo "\r\n\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    while ( $this->villages->next( ) )
    {
        echo "\t\t<tr>\r\n\t\t\t<td class=\"nam\"><a href=\"village3.php?id=";
        echo $this->villages->row['id'];
        echo "\">";
        echo $this->villages->row['village_name'];
        echo "</a>";
        if ( $this->villages->row['is_capital'] )
        {
            echo " ";
            echo "<s";
            echo "pan class=\"none3\">(";
            echo LANGUI_PROFILE_T25;
            echo ")</span>";
        }
        echo "</td>";
        echo '<td><a href="build.php?bid=17&vid2='. $this->villages->row['id'] .'"><img src="core-s/st-s/default/img/r/6.gif"></a></td>';
        echo '<td><a href="v2v.php?id='. $this->villages->row['id'] .'"><img src="core-s/st-s/x.gif" class="att_all"></a></td>';
        echo "\r\n\t\t\t<td class=\"hab\">";
        echo $this->villages->row['people_count'];
        echo "</td>\r\n\t\t\t<td class=\"aligned_coords\"><div class=\"cox\">(";
        echo $this->villages->row['rel_x'];
        echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
        echo $this->villages->row['rel_y'];
        echo ")</div></td>";
		if ( $this->isAdmin )
		{
			echo '<td><a href="Editp.php?t=1&v='.$this->villages->row['id'].'"><img title="تعديل" src="core-s/st-s/default/img/f/edit.gif" /></a></td>';
		}
		echo "\r\n\t\t</tr>\r\n\t\t";
    }
    echo "\t</tbody>\r\n</table>\r\n\r\n";
}
else if ( $this->selectedTabIndex == 1 )
{
    echo "<form action=\"profile.php\" enctype=\"multipart/form-data\" method=\"POST\">\r\n\t<input type=\"hidden\" name=\"e\" value=\"1\" />\r\n\t<input type=\"hidden\" name=\"oldavatar\" value=\"";
    echo htmlspecialchars( $this->profileData['avatar'] );
    echo "\" />\r\n\t<table cellpadding=\"1\" cellspacing=\"1\" id=\"edit\" class=\"vip\">\r\n\t\t<thead>\r\n\t\t\t<tr>\r\n\t\t\t\t<th colspan=\"3\">";
    echo LANGUI_PROFILE_T7;
    echo " ";
    echo $this->profileData['name'];
    echo "</th>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td colspan=\"2\">";
    echo LANGUI_PROFILE_T8;
    echo ":</td>\r\n\t\t\t\t<td>";
    echo LANGUI_PROFILE_T9;
    echo ":</td>\r\n\t\t\t</tr>\r\n\t\t</thead>\r\n\t\t<tbody>\r\n\t\t\t<tr>\r\n\t\t\t\t<td colspan=\"2\" class=\"empty\"></td><td class=\"empty\"></td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>";
    echo LANGUI_PROFILE_T26;
    echo ":</th>\r\n\t\t\t\t<td class=\"birth\">\r\n\t\t\t\t\t<input tabindex=\"3\" type=\"text\" name=\"jahr\" value=\"";
    if ( 0 < $this->birthDate['year'] )
    {
        echo $this->birthDate['year'];
    }
    echo "\" maxlength=\"4\" class=\"text year\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "elect tabindex=\"2\" name=\"monat\" size=\"0\" class=\"dropdown\">\r\n\t\t\t\t\t\t<option value=\"0\"></option>\r\n\t\t\t\t\t\t<option value=\"1\"";
    if ( $this->birthDate['month'] == 1 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T27;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"2\"";
    if ( $this->birthDate['month'] == 2 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T28;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"3\"";
    if ( $this->birthDate['month'] == 3 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T29;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"4\"";
    if ( $this->birthDate['month'] == 4 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T30;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"5\"";
    if ( $this->birthDate['month'] == 5 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T31;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"6\"";
    if ( $this->birthDate['month'] == 6 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T32;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"7\"";
    if ( $this->birthDate['month'] == 7 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T33;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"8\"";
    if ( $this->birthDate['month'] == 8 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T34;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"9\"";
    if ( $this->birthDate['month'] == 9 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T35;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"10\"";
    if ( $this->birthDate['month'] == 10 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T36;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"11\"";
    if ( $this->birthDate['month'] == 11 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T37;
    echo "</option>\r\n\t\t\t\t\t\t<option value=\"12\"";
    if ( $this->birthDate['month'] == 12 )
    {
        echo " selected=\"selected\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T38;
    echo "</option>\r\n\t\t\t\t\t</select>\r\n\t\t\t\t\t<input tabindex=\"1\" class=\"text day\" type=\"text\" name=\"tag\" value=\"";
    if ( 0 < $this->birthDate['day'] )
    {
        echo $this->birthDate['day'];
    }
    echo "\" maxlength=\"2\">\r\n\t\t\t\t</td>\r\n\t\t\t\t<td rowspan=\"8\" class=\"desc1\"><textarea tabindex=\"7\" name=\"be1\" class=\"AddMdal\">";
    echo $this->profileData['description1'];
    echo "</textarea></td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>";
    echo LANGUI_PROFILE_T16;
    echo ":</th>\r\n\t\t\t\t<td class=\"gend\">\r\n\t\t\t\t\t<label><input class=\"radio\" type=\"radio\" name=\"mw\" value=\"0\"";
    if ( $this->profileData['gender'] == 0 )
    {
        echo "  checked=\"\" tabindex=\"4\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T39;
    echo "</label>\r\n\t\t\t\t\t<label><input class=\"radio\" type=\"radio\" name=\"mw\" value=\"1\"";
    if ( $this->profileData['gender'] == 1 )
    {
        echo "  checked=\"\" tabindex=\"4\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T40;
    echo "</label>\r\n\t\t\t\t\t<label><input class=\"radio\" type=\"radio\" name=\"mw\" value=\"2\"";
    if ( $this->profileData['gender'] == 2 )
    {
        echo "  checked=\"\" tabindex=\"4\"";
    }
    echo ">";
    echo LANGUI_PROFILE_T41;
    echo "</label>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>";
    echo LANGUI_PROFILE_T19;
    echo ":</th>\r\n\t\t\t\t<td><input tabindex=\"5\" type=\"text\" name=\"ort\" value=\"";
    echo htmlspecialchars( $this->profileData['house_name'] );
    echo "\" maxlength=\"30\" class=\"text\" /></td>\r\n\t\t\t</tr>\r\n\t\t\t\r\n\t\t\t<tr>\r\n\t\t\t\t<th>";
    echo LANGUI_PROFILE_T42;
    echo ":</th>\r\n\t\t\t\t<td><input tabindex=\"6\" type=\"text\" name=\"dname\" value=\"";
    echo htmlspecialchars( $this->profileData['village_name'] );
    echo "\" maxlength=\"20\" class=\"text\" /></td>\r\n\t\t\t</tr>\r\n ";
              /*
echo" <tr>\r\n\t\t\t  <th>";
    echo LANGUI_PROFILE_T71;
    echo ":</th>\r\n\t\t\t  <td><input tabindex=\"10\" type=\"file\" name=\"avatar\" class=\"text\" /></td>\r\n\t      </tr>\r\n\t\t\t  "; */
    echo" <tr><td colspan=\"2\" class=\"empty\"></td></tr>";
    echo"\r\n\t\t\t<tr><td colspan=\"2\" class=\"desc2\"><textarea tabindex=\"8\" name=\"be2\">";
    echo $this->profileData['description2'];
    echo "</textarea></td></tr>\r\n\t\t</tbody>";
echo "\r\n\t</table>\r\n\r\n\t";

?>
<?php
echo "\r\n\t</table>\r\n\r\n\t";
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"medals\">\r\n\t\t<thead>\r\n\t\t\t<tr><th colspan=\"4\">";
    echo LANGUI_PROFILE_T43;
    echo "</th></tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>";
    echo LANGUI_PROFILE_T44;
    echo "</td>\r\n\t\t\t\t<td>";
    echo LANGUI_PROFILE_T45;
    echo "</td>\r\n\t\t\t\t<td>";
    echo LANGUI_PROFILE_T46;
    echo "</td><td class=\"select-all-codes\">";
    echo LANGUI_PROFILE_T47;
    echo "</td>\r\n\t\t\t</tr>\r\n\t\t</thead>\r\n\t\t<tbody>\r\n\t\t\t";
    $medals = explode( ",", $this->profileData['medals'] );
    foreach ( $medals as $medal )
    {
        $week = explode( ":", $medal );
        $rank = explode( ":", $medal );
        $index = explode( ":", $medal );
        list( $index, $rank, $week) = $index;
        if ( !isset( $this->gameMetadata['medals'][$index] ) )
        {
            continue;
        }
        $medalData = $this->gameMetadata['medals'][$index];
        if ( $index == 0 )
        {
            $rank = 1;
        }
        echo "\t\t\t<tr>\r\n\t\t\t   <td class=\"typ\">";
        echo constant( "medal_row_".$medalData['textIndex'] );
        echo "</td>\r\n\t\t\t   <td class=\"ra\">";
        echo $rank;
        echo "</td>\r\n\t\t\t   <td class=\"we\">";
        echo $week;
        echo "</td><td class=\"bb\"><a class=\"clkM\" id=\"M0\" href=\"#edit\" onclick=\"AddMedals()\">[#"; echo intval( $medalData['BBCode'] ) + intval( $week ) * 10 + ( intval( $rank ) - 1 );"</a></td>";
        echo "]</td>\r\n\t\t\t</tr>\r\n\t\t\t";
    }
    echo "\t\t</tbody>\r\n\t</table>\r\n\t<p class=\"btn\"><input type=\"image\" value=\"\" tabindex=\"9\" name=\"s1\" id=\"btn_ok\" class=\"dynamic_img\" src=\"core-s/st-s/x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\"></p>\r\n</form>\r\n";
    
}
else if ( $this->selectedTabIndex == 2 )
{
    
    echo "<form action=\"profile.php?t=2\" method=\"POST\">\r\n<input type=\"hidden\" name=\"e\" value=\"2\">\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"change_mail\" class=\"account\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo LANGUI_PROFILE_T48;
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr><td class=\"note\" colspan=\"2\">";
    echo LANGUI_PROFILE_T49;
    echo "</td></tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_PROFILE_T50;
    echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"password\" name=\"pw1\" maxlength=\"20\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_PROFILE_T51;
    echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"password\" name=\"pw2\" maxlength=\"20\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_PROFILE_T51;
    echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"password\" name=\"pw3\" maxlength=\"20\"></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n";
	list ($activ, $email_new, $code_email_alt, $code_email_new) = explode (':', $this->data['email_alt']);
	if($activ == 0){
	echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"change_mail\" class=\"account\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo LANGUI_PROFILE_T52;
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr><td class=\"note\" colspan=\"2\">";
    echo LANGUI_PROFILE_T53;
    echo "</td></tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_PROFILE_T54;
    echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"text\" name=\"email_alt\" maxlength=\"50\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_PROFILE_T55;
    echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"text\" name=\"email_neu\" maxlength=\"50\"></td>\r\n\t\t</tr>";
    echo "\r\n\t</tbody>\r\n</table>";
	}else{
	?>
	<table cellpadding="1" cellspacing="1" id="change_mail" class="account"><thead><tr>
	<th colspan="2" class="process">يتم تغيير البريد الإلكتروني <a href="profile.php?t=2&email_abbrechen"><img class="del" src="core-s/st-s/x.gif" title="أنهاء العملية" alt="أنهاء العملية"></a></th>
	</tr></thead>
	<tbody><tr>
	<td class="note" colspan="2">لقد تم إرسال كود تفعيل لبريدك الإلكتروني الجديد وكود تفعيل لبريدك الإلكتروني القديم. قم بإدخال  كلاهما في الأماكن المخصصة هنا.</td>
	</tr>
	<tr>
	<th>كود التفعيل الخاص بالبريد الإلكتروني القديم</th>
	<td><input class="text" type="text" name="code_email_alt" maxlength="5"></td>
	</tr>
	<tr>
	<th>كود التفعيل الخاص بالبريد الإلكتروني الجديد</th>
	<td><input class="text" type="text" name="code_email_neu" maxlength="5"></td>
	</tr></tbody></table>
	
	<?php } ?>
	</tbody></table>
			
	</td>
	</tr>
	</tbody></table>
	</td>
	</tr>
	</tbody>
	</table>
	<?php
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"del_acc\" class=\"account\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo LANGUI_PROFILE_T6;
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr><td class=\"note\" colspan=\"2\">";
    echo LANGUI_PROFILE_T64;
    echo "</td></tr>\r\n\t\t";
    if ( $this->isPlayerInDeletionProgress( ) )
    {
        echo "\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"count\">\r\n\t\t\t\t";
        if ( $this->canCancelPlayerDeletionProcess( ) )
        {
            echo "<a href=\"profile.php?t=2&qid=";
            echo $this->getPlayerDeletionId( );
            echo "\"><img class=\"del\" src=\"core-s/st-s/x.gif\" alt=\"";
            echo LANGUI_PROFILE_T65;
            echo "\" title=\"";
            echo LANGUI_PROFILE_T65;
            echo "\"> ";
        }
        echo "</a>";
        echo LANGUI_PROFILE_T66;
        echo " ";
        echo "<s";
        echo "pan id=\"timer1\">";
        echo $this->getPlayerDeletionTime( );
        echo "</span> ";
        echo time_hour_lang;
        echo "\t\t\t</td>\r\n\t\t</tr>\r\n\t\t";
    }
    else
    {
        echo "\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_PROFILE_T6;
        echo "</th>\r\n\t\t\t<td class=\"del_selection\">\r\n\t\t\t\t<label><input class=\"radio\" type=\"radio\" name=\"del\" value=\"1\"> ";
        echo LANGUI_PROFILE_T67;
        echo "</label>\r\n\t\t\t\t<label><input class=\"radio\" type=\"radio\" name=\"del\" value=\"0\" checked=\"\"> ";
        echo LANGUI_PROFILE_T68;
        echo "</label>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_PROFILE_T69;
        echo ":</th>\r\n\t\t\t<td><input class=\"text\" type=\"password\" name=\"del_pw\" maxlength=\"20\"></td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo "\t</tbody>\r\n</table>\r\n";
    if ( !$this->isPlayerInDeletionProgress( ) )
    {
        echo "<p class=\"btn\"><input type=\"image\" value=\"\" name=\"s1\" id=\"btn_save\" class=\"dynamic_img\" src=\"core-s/st-s/x.gif\" alt=\"";
        echo text_save_lang;
        echo "\"></p>";
    }
    echo "</form>\r\n";

}
?>
<style>
	@media screen and (max-width: 900px){
	body {
    zoom: 70%;
	}
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/d3js/6.6.1/d3.min.js"></script>
</script>
 <script type="text/javascript" language="javascript">
 
    let sellectAllCodes=document.querySelector(".select-all-codes");
    let recivedCodes= document.querySelectorAll(".clkM");
    
    sellectAllCodes.addEventListener("click",()=>{
        displayAllCodes();
    })
    recivedCodes.forEach(e=>{
        e.addEventListener("click",()=>{
            document.querySelector(".AddMdal").innerText=e.innerText
        })
    })
    function displayAllCodes()
    {
        
        let allCodes="";
        document.querySelector(".AddMdal").innerText="";
         recivedCodes.forEach(e=>{
             allCodes+=(e.innerText+"");
         })
            document.querySelector(".AddMdal").innerText=allCodes;
        
        
    }
    
   
</script>
</body>
</html>