<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php
include("core-s/conf-s/tcex-con.php");
$link = mysql_connect($AppConfig['db']['webhost'],$AppConfig['db']['webuser'],$AppConfig['db']['webpassword']) or die(mysql_error());
mysql_select_db($AppConfig['db']['webdatabase'],$link) or die(mysql_error());


if($_POST['submit']){
$q = "SELECT * FROM g_settings order by cur_week DESC LIMIT 0, 1";
$result = mysql_query( $q );
if ( mysql_num_rows( $result ) )
{
    $row = mysql_fetch_assoc( $result );
    $week = $row['cur_week'] + 1;
}
else
{
    $week = "1";
}
$result = mysql_query( "SELECT * FROM p_players WHERE id > 0 ORDER BY week_dev_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "1:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_players SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_dev_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_players WHERE id > 0 ORDER BY week_attack_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "2:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_players SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_attack_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_players WHERE id > 0 ORDER BY week_defense_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "3:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_players SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_defense_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_players WHERE id > 0 ORDER BY week_thief_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "4:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_players SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_thief_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
if ( $week == "1" )
{
    if ( !mysql_query( "UPDATE p_alliances SET medals='::'" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_alliances WHERE id > 0 ORDER BY week_dev_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "5:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_alliances SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_dev_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_alliances WHERE id > 0 ORDER BY week_attack_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "6:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_alliances SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_attack_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_alliances WHERE id > 0 ORDER BY week_defense_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "7:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_alliances SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_defense_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
$result = mysql_query( "SELECT * FROM p_alliances WHERE id > 0 ORDER BY week_thief_points DESC Limit 10" );
$i = 0;
while ( $row = mysql_fetch_array( $result ) )
{
    $i++;
    $medal = "8:{$i}:{$week}";
    $id = $row['id'];
    if ( !mysql_query( "UPDATE p_alliances SET medals=CONCAT_WS(',',  medals, '{$medal}') WHERE id='{$id}' AND week_thief_points > 0" ) )
    {
        exit( mysql_error( ) );
    }
}
if ( !mysql_query( "UPDATE g_settings SET cur_week='{$week}'" ) )
{
    exit( mysql_error( ) );
}
if ( !mysql_query( "UPDATE p_players   SET week_dev_points='0',  week_attack_points='0', week_defense_points='0', week_thief_points='0'" ) )
{
    exit( mysql_error( ) );
}
if ( !mysql_query( "UPDATE p_alliances SET week_dev_points='0',  week_attack_points='0', week_defense_points='0', week_thief_points='0'" ) )
{
    exit( mysql_error( ) );
}

echo "<p align=\"center\"><font color=\"blue\" size=\"5\"> تم توزيع الأوسمة لأفضل 10 لاعبين </font></p>";
echo "<p align=\"center\"><font color=\"blue\" size=\"5\"> تم توزيع الأسمة لأفضل 10 تحالفات </font></p>";
echo "<p align=\"center\"><font color=\"blue\" size=\"5\"> تم تحديث الأسبوع </font></p>";
echo "<p align=\"center\"><font color=\"blue\" size=\"5\"> تم تصفير نقاط اللاعبين </font></p>";
echo "<p class=\"f16\" align=\"center\">\r\n<a href=\"village1.php\"><font size=\"4\" color=\"green\">\r\n<span style=\"text-decoration: none\">» إلى الأمام</span></font></a></p>";

}

?>
<form action="wesaaam.php" method="POST">
<table cellpadding="1" cellspacing="1" id="links">
<tr>
<td colspan="2">توزيع الأوسمة</td><br />
</tr>

<tr>
<td colspan="2"><input name="submit" type="submit" value="توزيع"></td>
</tr>
</table>
</form>  
</body>
</html>